POST {{local_api}}/member/login
Content-Type: application/json

{
    "email": "tnswh2023@naver.com"
}

### register
POST {{local_api}}/member/register
Content-Type: application/json

{
    "email": "tnswh2023@naver.com"
}