### createRoom
POST {{local_api}}/api/v1/room
Content-Type: application/json

{
  "name": "room1",
  "password": "1234",
  "isPrivate": false
}

###
GET {{local_api}}/api/v1/room/all
Content-Type: application/json

###
GET {{local_api}}/api/v1/room/5019193e-6fb1-4e97-a118-38516d9370c6
Content-Type: application/json

###
POST {{local_api}}/api/v1/room/omok
Content-Type: application/json

{
  "roomId": "5019193e-6fb1-4e97-a118-38516d9370c6",
  "turn": "black",
  "x": 4,
  "y": 0
}

